[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_SERVER_URL,VITE_API_URL"
  SECRETS_SCAN_OMIT_PATHS = "client/dist,dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
