import { useState, useEffect } from 'react';
import { useNavigate, useParams, Link, useSearchParams } from 'react-router-dom';
import { createCourse, getCourseById, updateCourse, createModule, createLesson, deleteModule, deleteLesson, togglePublish } from '../api/courseApi';
import { generateCourseDescription, generateLessonSummary } from '../api/aiApi';
import toast from 'react-hot-toast';
import CustomSelect from '../components/common/CustomSelect';
import { CATEGORIES, DIFFICULTIES, STRUCTURE_TYPES } from '../utils/constants';
import { 
  HiOutlineCloudUpload, 
  HiOutlineCurrencyDollar, 
  HiOutlineClock, 
  HiOutlineSparkles, 
  HiOutlineBookOpen, 
  HiOutlineAcademicCap, 
  HiOutlineTag,
  HiOutlinePhotograph,
  HiOutlineCheckCircle,
  HiOutlineTrash,
  HiOutlinePlus,
  HiOutlineDocumentText,
  HiOutlinePlay,
  HiOutlineArrowLeft,
  HiOutlineGlobeAlt,
  HiOutlineEyeOff,
  HiOutlineArrowRight
} from 'react-icons/hi';
import './CourseCreate.css';

const CourseCreate = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [searchParams, setSearchParams] = useSearchParams();
  const isEdit = !!id;

  const activeTab = searchParams.get('tab') || 'details';
  const setActiveTab = (tab) => setSearchParams({ tab });

  const [form, setForm] = useState({
    title: '',
    description: '',
    shortDescription: '',
    category: 'web-development',
    difficulty: 'beginner',
    structureType: 'topic-based',
    price: 0,
    estimatedDuration: '',
  });
  const [imageFile, setImageFile] = useState(null);
  const [existingThumbnail, setExistingThumbnail] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isPublished, setIsPublished] = useState(false);
  const [modules, setModules] = useState([]);
  const [extraWeeks, setExtraWeeks] = useState([]);
  const [newModTitles, setNewModTitles] = useState({});
  
  // Lesson outline states
  const [activeModuleId, setActiveModuleId] = useState(null);
  const [lessonFile, setLessonFile] = useState(null);
  const [lessonForm, setLessonForm] = useState({
    title: '',
    type: 'lecture',
    videoUrl: '',
    content: '',
  });

  const [aiLoading, setAiLoading] = useState(false);

  const handleGenerateCourseDesc = async () => {
    if (!form.title.trim()) {
      toast.error('Please enter a course title first to guide the AI!');
      return;
    }
    setAiLoading(true);
    try {
      const res = await generateCourseDescription(form.title, form.category);
      setForm(prev => ({ ...prev, description: res.data.data.description }));
      toast.success('Course description generated by Gemini AI!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'AI generation failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleGenerateLessonSummary = async () => {
    if (!lessonForm.title.trim()) {
      toast.error('Please enter a lesson title first to guide the AI!');
      return;
    }
    setAiLoading(true);
    try {
      const res = await generateLessonSummary(lessonForm.title, lessonForm.content || '');
      setLessonForm(prev => ({ ...prev, content: res.data.data.summary }));
      toast.success('Lesson summary generated by Gemini AI!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'AI generation failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleAddLesson = async (e, moduleId) => {
    e.preventDefault();
    if (!lessonForm.title.trim()) return;
    try {
      let res;
      if (lessonFile || ['notes', 'dpp-pdf', 'document'].includes(lessonForm.type)) {
        const formData = new FormData();
        formData.append('title', lessonForm.title);
        formData.append('type', lessonForm.type);
        formData.append('content', lessonForm.content);
        formData.append('videoUrl', lessonForm.videoUrl);
        formData.append('courseId', id);
        if (lessonFile) {
          formData.append('attachments', lessonFile);
        }
        res = await createLesson(moduleId, formData);
      } else {
        res = await createLesson(moduleId, { ...lessonForm, courseId: id });
      }
      
      const updated = modules.map(m => {
        if (m._id === moduleId) {
          return { ...m, lessons: [...(m.lessons || []), res.data.data] };
        }
        return m;
      });
      setModules(updated);
      
      setLessonForm({ title: '', type: 'lecture', videoUrl: '', content: '' });
      setLessonFile(null);
      setActiveModuleId(null);
      toast.success('Lesson successfully added!');
    } catch (err) {
      console.error(err);
      toast.error('Failed to add lesson to module');
    }
  };

  useEffect(() => {
    if (isEdit) {
      const loadCourse = async () => {
        try {
          const res = await getCourseById(id);
          const c = res.data.data;
          setForm({
            title: c.title,
            description: c.description,
            shortDescription: c.shortDescription || '',
            category: c.category,
            difficulty: c.difficulty,
            structureType: c.structureType,
            price: c.price || 0,
            estimatedDuration: c.estimatedDuration || '',
          });
          setExistingThumbnail(c.thumbnail || null);
          setModules(c.modules || []);
          setIsPublished(c.isPublished || false);
        } catch {
          toast.error('Failed to load course for editing');
        }
      };
      loadCourse();
    }
  }, [id, isEdit]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const formData = new FormData();
      Object.keys(form).forEach(key => formData.append(key, form[key]));
      if (imageFile) formData.append('thumbnail', imageFile);

      if (isEdit) {
        await updateCourse(id, formData);
        toast.success('Course details saved! Redirecting to curriculum builder...');
        setActiveTab('curriculum');
      } else {
        const res = await createCourse(formData);
        toast.success('Course created! Redirecting to curriculum builder...');
        navigate(`/course/${res.data.data._id}/edit?tab=curriculum`);
      }
    } catch {
      toast.error('Failed to save course');
    } finally {
      setLoading(false);
    }
  };

  const handleAddModuleForWeek = async (e, weekNum) => {
    e.preventDefault();
    const title = newModTitles[weekNum];
    if (!title || !title.trim() || !id) return;
    try {
      const res = await createModule(id, { title: title.trim(), week: weekNum });
      setModules([...modules, res.data.data]);
      setNewModTitles(prev => ({ ...prev, [weekNum]: '' }));
      toast.success(`Module added to Week ${weekNum}!`);
    } catch {
      toast.error('Failed to add module');
    }
  };

  const handleDeleteModule = async (moduleId) => {
    if (!window.confirm('Are you sure you want to delete this module?')) return;
    try {
      await deleteModule(moduleId);
      setModules(modules.filter(m => m._id !== moduleId));
      toast.success('Module deleted!');
    } catch {
      toast.error('Failed to delete module');
    }
  };

  const handleDeleteLesson = async (moduleId, lessonId) => {
    if (!window.confirm('Are you sure you want to delete this lesson?')) return;
    try {
      await deleteLesson(lessonId);
      setModules(modules.map(m => {
        if (m._id === moduleId) {
          return { ...m, lessons: m.lessons.filter(l => l._id !== lessonId) };
        }
        return m;
      }));
      toast.success('Lesson deleted!');
    } catch {
      toast.error('Failed to delete lesson');
    }
  };

  const handleTogglePublish = async () => {
    try {
      const res = await togglePublish(id);
      setIsPublished(res.data.data.isPublished);
      toast.success(`Course ${res.data.data.isPublished ? 'published' : 'unpublished'} successfully!`);
    } catch {
      toast.error('Failed to toggle publish status');
    }
  };

  const getImageUrl = (path) => {
    if (!path) return null;
    if (path.startsWith('http://') || path.startsWith('https://')) return path;
    const apiURL = import.meta.env.VITE_API_URL || '';
    const baseURL = apiURL.replace(/\/api\/?$/, '').replace(/\/$/, '');
    const cleanPath = path.startsWith('/') ? path : `/${path}`;
    return `${baseURL}${cleanPath}`;
  };

  const previewThumbnailUrl = imageFile ? URL.createObjectURL(imageFile) : getImageUrl(existingThumbnail);

  return (
    <div className="create-course-page animate-page-enter">
      
      {/* Header Banner */}
      <div className="create-course-header-banner">
        <div className="space-y-1">
          <div className="flex items-center gap-3">
            <Link to="/dashboard" className="text-xs font-bold text-slate-500 hover:text-indigo-600 dark:hover:text-indigo-400 flex items-center gap-1 transition-colors">
              <HiOutlineArrowLeft size={14} /> Back to Dashboard
            </Link>
            <span className="text-slate-300 dark:text-slate-700">•</span>
            <span className="text-xs font-extrabold uppercase tracking-wider text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/40 px-3 py-0.5 rounded-full border border-indigo-200 dark:border-indigo-500/20 inline-flex items-center gap-1.5">
              <HiOutlineSparkles size={13} /> Instructor Studio
            </span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-black font-heading text-slate-900 dark:text-white tracking-tight">
            {isEdit ? 'Edit' : 'Create New'} <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">Course Workspace</span>
          </h1>
          <p className="text-sm text-slate-600 dark:text-slate-400 font-medium">
            Configure course meta, pricing details, cover image, and curriculum modules.
          </p>
        </div>

        {isEdit && (
          <div className="flex items-center gap-3">
            {/* Live / Draft Status Badge */}
            <div className={`px-4 py-2 rounded-2xl text-xs font-extrabold flex items-center gap-2 border transition-all shadow-sm ${
              isPublished 
                ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/30 dark:bg-emerald-950/40' 
                : 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/30 dark:bg-amber-950/40'
            }`}>
              <span className="relative flex h-2.5 w-2.5">
                <span className={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${
                  isPublished ? 'bg-emerald-400' : 'bg-amber-400'
                }`}></span>
                <span className={`relative inline-flex rounded-full h-2.5 w-2.5 ${
                  isPublished ? 'bg-emerald-500' : 'bg-amber-500'
                }`}></span>
              </span>
              {isPublished ? (
                <span className="flex items-center gap-1.5">
                  <HiOutlineGlobeAlt className="text-emerald-500" size={15} /> Published & Live
                </span>
              ) : (
                <span className="flex items-center gap-1.5">
                  <HiOutlineEyeOff className="text-amber-500" size={15} /> Draft Mode
                </span>
              )}
            </div>

            {/* Toggle Publish Action Button */}
            <button 
              type="button" 
              className={`px-5 py-2.5 rounded-2xl text-xs font-extrabold flex items-center gap-2 transition-all duration-300 shadow-lg cursor-pointer ${
                isPublished 
                  ? 'bg-slate-900/60 dark:bg-white/5 border border-slate-700/60 text-slate-300 hover:text-amber-400 hover:border-amber-500/40 hover:bg-amber-500/10 backdrop-blur-md hover:scale-[1.02] active:scale-95' 
                  : 'bg-gradient-to-r from-emerald-500 via-teal-500 to-emerald-600 text-white shadow-emerald-500/30 hover:shadow-emerald-500/50 hover:scale-[1.03] active:scale-95 border border-emerald-400/30'
              }`}
              onClick={handleTogglePublish}
            >
              {isPublished ? (
                <>
                  <HiOutlineEyeOff size={16} /> Unpublish Course
                </>
              ) : (
                <>
                  <HiOutlineGlobeAlt size={16} className="animate-pulse" /> Publish Course Live
                </>
              )}
            </button>
          </div>
        )}
        {isEdit && (
          <div className="flex items-center justify-between flex-wrap gap-4 mt-6 p-2 bg-slate-100/80 dark:bg-slate-900/90 border border-slate-200/90 dark:border-slate-800/90 rounded-2xl shadow-sm backdrop-blur-md">
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setActiveTab('details')}
                className={`px-5 py-2.5 rounded-xl text-xs font-extrabold flex items-center gap-2 transition-all duration-200 cursor-pointer ${
                  activeTab === 'details'
                    ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md shadow-indigo-500/20'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/60 dark:hover:bg-white/5'
                }`}
              >
                <HiOutlineDocumentText size={16} /> 1. Course Details & Settings
              </button>

              <button
                type="button"
                onClick={() => setActiveTab('curriculum')}
                className={`px-5 py-2.5 rounded-xl text-xs font-extrabold flex items-center gap-2 transition-all duration-200 cursor-pointer ${
                  activeTab === 'curriculum'
                    ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md shadow-indigo-500/20'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200/60 dark:hover:bg-white/5'
                }`}
              >
                <HiOutlineBookOpen size={16} /> 2. Curriculum & Lesson Builder ({modules.length})
              </button>
            </div>

            <div className="text-xs font-bold text-slate-500 dark:text-slate-400 px-3 hidden sm:block">
              {activeTab === 'details' ? 'Editing Course Metadata & Pricing' : 'Building Modules & Lessons'}
            </div>
          </div>
        )}
      </div>

      <div className={`create-course-layout ${isEdit ? 'is-edit' : 'is-create'}`}>
        
        {/* Main Form (Tab 1) */}
        {(!isEdit || activeTab === 'details') && (
        <form onSubmit={handleSubmit} className="create-course-form" id="course-create-form">
          
          <div className="space-y-6">
            
            {/* Title Input */}
            <div className="space-y-2">
              <label htmlFor="course-title" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                Course Title
              </label>
              <input 
                id="course-title" 
                type="text" 
                className="w-full px-4 py-3.5 bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl text-slate-900 dark:text-white placeholder-slate-400 font-semibold text-base focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all" 
                placeholder="e.g. Master Full-Stack Web Development with React & Node" 
                value={form.title} 
                onChange={(e) => setForm({ ...form, title: e.target.value })} 
                required 
              />
            </div>

            {/* Short Description */}
            <div className="space-y-2">
              <label htmlFor="course-short-desc" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                Short Subtitle Summary
              </label>
              <input 
                id="course-short-desc" 
                type="text" 
                className="w-full px-4 py-3.5 bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl text-slate-900 dark:text-white placeholder-slate-400 font-medium text-sm focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all" 
                placeholder="Brief high-level pitch of what students will learn..." 
                value={form.shortDescription} 
                onChange={(e) => setForm({ ...form, shortDescription: e.target.value })} 
              />
            </div>

            {/* Full Description with AI Generate Button */}
            <div className="space-y-2">
              <div className="flex justify-between items-center">
                <label htmlFor="course-description" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                  Detailed Course Description
                </label>
                <button
                  type="button"
                  className="ai-generate-btn"
                  onClick={handleGenerateCourseDesc}
                  disabled={aiLoading}
                >
                  <HiOutlineSparkles size={14} />
                  <span>{aiLoading ? 'Generating...' : 'Generate with Gemini AI'}</span>
                </button>
              </div>
              <textarea 
                id="course-description" 
                className="w-full p-4 bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl text-slate-900 dark:text-white placeholder-slate-400 font-medium text-sm focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all textarea-large" 
                placeholder="Write comprehensive course overview, learning outcomes, and requirements..." 
                value={form.description} 
                onChange={(e) => setForm({ ...form, description: e.target.value })} 
                required 
              />
            </div>

            {/* Category & Difficulty Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              <div className="space-y-2">
                <label htmlFor="course-category" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <HiOutlineTag className="text-indigo-500" size={16} /> Category
                </label>
                <CustomSelect
                  id="course-category"
                  name="category"
                  value={form.category}
                  onChange={(e) => setForm({ ...form, category: e.target.value })}
                  options={CATEGORIES}
                  icon={HiOutlineTag}
                  showSearch={true}
                />
              </div>

              <div className="space-y-2">
                <label htmlFor="course-diff" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <HiOutlineAcademicCap className="text-emerald-500" size={16} /> Difficulty Level
                </label>
                <CustomSelect
                  id="course-diff"
                  name="difficulty"
                  value={form.difficulty}
                  onChange={(e) => setForm({ ...form, difficulty: e.target.value })}
                  options={DIFFICULTIES}
                  icon={HiOutlineAcademicCap}
                  showColorDot={true}
                />
              </div>
            </div>

            {/* Structure, Price & Duration Row (Side-by-Side Boxes) */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
              <div className="space-y-2">
                <label htmlFor="course-structure" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <HiOutlineBookOpen className="text-blue-500" size={16} /> Structure Mode
                </label>
                <CustomSelect
                  id="course-structure"
                  name="structureType"
                  value={form.structureType}
                  onChange={(e) => setForm({ ...form, structureType: e.target.value })}
                  options={STRUCTURE_TYPES}
                  icon={HiOutlineBookOpen}
                  disabled={isEdit}
                />
              </div>

              <div className="space-y-2">
                <label htmlFor="course-price" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <HiOutlineCurrencyDollar className="text-emerald-500" size={16} /> Course Price ($)
                </label>
                <div className="relative flex items-center">
                  <span className="absolute left-4 z-10 text-slate-400 font-extrabold">$</span>
                  <input 
                    id="course-price" 
                    type="number" 
                    min="0" 
                    step="0.01" 
                    style={{ paddingLeft: '2.25rem' }} 
                    className="w-full pr-4 py-3.5 bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl text-slate-900 dark:text-white font-semibold text-sm focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all" 
                    value={form.price} 
                    onChange={(e) => setForm({ ...form, price: parseFloat(e.target.value) || 0 })} 
                  />
                </div>
                {/* Price Presets */}
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {[
                    { label: 'Free', val: 0 },
                    { label: '$29', val: 29 },
                    { label: '$49', val: 49 },
                    { label: '$99', val: 99 }
                  ].map((preset) => (
                    <button
                      key={preset.label}
                      type="button"
                      className={`px-2.5 py-1 rounded-xl text-[11px] font-extrabold transition-all duration-200 ${
                        form.price === preset.val
                          ? 'bg-emerald-600 text-white shadow-sm ring-2 ring-emerald-500/30'
                          : 'bg-slate-100 text-slate-600 hover:bg-emerald-50 hover:text-emerald-600 dark:bg-white/5 dark:text-slate-300 dark:hover:bg-emerald-500/10 dark:hover:text-emerald-300 border border-slate-200/80 dark:border-white/5'
                      }`}
                      onClick={() => setForm({ ...form, price: preset.val })}
                    >
                      {preset.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="space-y-2">
                <label htmlFor="course-duration" className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <HiOutlineClock className="text-purple-500" size={16} /> Est. Duration
                </label>
                <div className="relative flex items-center">
                  <HiOutlineClock className="pointer-events-none absolute left-3.5 z-10 text-slate-400" size={18} />
                  <input 
                    id="course-duration" 
                    type="text" 
                    style={{ paddingLeft: '2.75rem' }} 
                    placeholder="e.g. 4 weeks, 20 hrs" 
                    className="w-full pr-4 py-3.5 bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-800 rounded-2xl text-slate-900 dark:text-white font-semibold text-sm focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 transition-all" 
                    value={form.estimatedDuration} 
                    onChange={(e) => setForm({ ...form, estimatedDuration: e.target.value })} 
                  />
                </div>
                {/* Duration Presets (Balanced 3-column Grid) */}
                <div className="grid grid-cols-3 gap-1 pt-1">
                  {['2 Weeks', '4 Weeks', '8 Weeks', '12 Weeks', '30 Days', 'Self-Paced'].map((preset) => (
                    <button
                      key={preset}
                      type="button"
                      className={`px-2 py-1 rounded-xl text-[10px] font-extrabold transition-all duration-200 text-center truncate ${
                        form.estimatedDuration === preset
                          ? 'bg-purple-600 text-white shadow-sm ring-2 ring-purple-500/30'
                          : 'bg-slate-100 text-slate-600 hover:bg-purple-50 hover:text-purple-600 dark:bg-white/5 dark:text-slate-300 dark:hover:bg-purple-500/10 dark:hover:text-purple-300 border border-slate-200/80 dark:border-white/5'
                      }`}
                      onClick={() => setForm({ ...form, estimatedDuration: preset })}
                    >
                      {preset}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Custom Thumbnail Dropzone (Replaces ugly browser file button) */}
            <div className="space-y-2">
              <label className="block text-xs font-extrabold text-slate-700 dark:text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                <HiOutlinePhotograph className="text-pink-500" size={16} /> Cover Thumbnail Image
              </label>

              <div className="relative">
                <input 
                  id="course-thumbnail" 
                  type="file" 
                  accept="image/*" 
                  className="hidden" 
                  onChange={(e) => {
                    if (e.target.files && e.target.files[0]) {
                      setImageFile(e.target.files[0]);
                    }
                  }} 
                />
                
                {previewThumbnailUrl ? (
                  <div className="relative rounded-2xl overflow-hidden border border-slate-200 dark:border-white/10 group h-56 bg-slate-950 shadow-md">
                    <img 
                      src={previewThumbnailUrl} 
                      alt="Course thumbnail preview" 
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" 
                    />
                    <div className="absolute inset-0 bg-slate-950/60 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center gap-3 backdrop-blur-sm">
                      <label 
                        htmlFor="course-thumbnail" 
                        className="px-5 py-2.5 bg-white/20 hover:bg-white/30 text-white rounded-xl text-xs font-extrabold backdrop-blur-md cursor-pointer transition-all shadow-lg"
                      >
                        Change Image
                      </label>
                      {imageFile && (
                        <button 
                          type="button" 
                          onClick={() => setImageFile(null)} 
                          className="px-5 py-2.5 bg-rose-500/80 hover:bg-rose-600 text-white rounded-xl text-xs font-extrabold backdrop-blur-md transition-all shadow-lg"
                        >
                          Remove Upload
                        </button>
                      )}
                    </div>
                  </div>
                ) : (
                  <label 
                    htmlFor="course-thumbnail" 
                    className="flex flex-col items-center justify-center p-10 border-2 border-dashed border-slate-300 dark:border-white/15 hover:border-indigo-500 dark:hover:border-indigo-500/50 rounded-2xl cursor-pointer bg-slate-50/70 dark:bg-slate-900/40 hover:bg-indigo-50/30 dark:hover:bg-indigo-500/5 transition-all duration-300 group text-center"
                  >
                    <div className="w-14 h-14 rounded-2xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mb-3 group-hover:scale-110 transition-transform duration-300 shadow-sm">
                      <HiOutlineCloudUpload size={30} />
                    </div>
                    <span className="text-sm font-extrabold text-slate-800 dark:text-slate-200">
                      Click or drag to upload course cover image
                    </span>
                    <span className="text-xs text-slate-400 font-medium mt-1">
                      PNG, JPG, WebP up to 5MB (16:9 ratio recommended)
                    </span>
                  </label>
                )}
              </div>
            </div>

          </div>

          <div className="pt-4 border-t border-slate-200 dark:border-white/5 flex flex-wrap items-center justify-between gap-4">
            {isEdit ? (
              <button
                type="button"
                className="px-6 py-3 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-200 font-extrabold text-xs rounded-2xl transition-all flex items-center gap-2 cursor-pointer"
                onClick={() => setActiveTab('curriculum')}
              >
                <HiOutlineBookOpen size={16} /> Open Curriculum Builder →
              </button>
            ) : (
              <div />
            )}

            <button 
              type="submit" 
              className="w-full sm:w-auto px-10 py-4 bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 hover:from-indigo-700 hover:to-pink-700 text-white rounded-2xl font-extrabold text-base shadow-lg shadow-indigo-500/25 hover:shadow-indigo-500/40 hover:scale-[1.01] active:scale-95 transition-all duration-300 disabled:opacity-50 flex items-center justify-center gap-2 cursor-pointer border border-white/20" 
              disabled={loading}
            >
              {loading ? (
                'Saving Changes...'
              ) : isEdit ? (
                <>
                  Save & Continue to Curriculum <HiOutlineArrowRight size={18} />
                </>
              ) : (
                <>
                  Create Course & Build Outline <HiOutlineArrowRight size={18} />
                </>
              )}
            </button>
          </div>
        </form>
        )}

        {/* Curriculum Outline Builder Column (Tab 2) */}
        {isEdit && activeTab === 'curriculum' && (
          <div className="create-course-outline">
            <div className="flex justify-between items-center pb-3 border-b border-slate-200 dark:border-slate-800">
              <div>
                <span className="text-[10px] font-extrabold uppercase tracking-widest text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/40 px-2.5 py-0.5 rounded-full border border-indigo-200 dark:border-indigo-500/20 inline-flex items-center gap-1">
                  <HiOutlineBookOpen size={12} /> Curriculum Builder
                </span>
                <h3 className="text-xl font-extrabold text-slate-900 dark:text-white font-heading mt-1">
                  Course Outline
                </h3>
              </div>
              <button 
                type="button" 
                className="px-4 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white rounded-2xl text-xs font-extrabold shadow-md hover:scale-105 active:scale-95 transition-all flex items-center gap-1.5" 
                onClick={() => {
                  const weeks = Array.from(new Set([1, ...modules.map(m => m.week || 1), ...extraWeeks]));
                  const nextWeek = Math.max(...weeks, 0) + 1;
                  setExtraWeeks([...extraWeeks, nextWeek]);
                }}
              >
                <HiOutlinePlus size={16} /> Add Week
              </button>
            </div>

            <div className="weeks-list space-y-5">
              {(() => {
                const weeks = Array.from(new Set([1, ...modules.map(m => m.week || 1), ...extraWeeks])).sort((a, b) => a - b);
                return weeks.map((weekNum) => {
                  const weekModules = modules.filter(m => (m.week || 1) === weekNum);
                  return (
                    <div key={weekNum} className="week-section p-5 border border-slate-200 dark:border-slate-800 rounded-3xl bg-slate-50/50 dark:bg-white/[0.01] shadow-sm">
                      <div className="flex items-center justify-between mb-4 pb-2 border-b border-slate-200 dark:border-slate-800">
                        <span className="text-sm font-extrabold text-indigo-600 dark:text-indigo-400 flex items-center gap-2">
                          <span className="w-7 h-7 rounded-xl bg-indigo-500/10 flex items-center justify-center font-bold text-xs">
                            W{weekNum}
                          </span>
                          Week {weekNum} Modules
                        </span>
                        <span className="text-xs font-bold text-slate-400">
                          {weekModules.length} {weekModules.length === 1 ? 'Module' : 'Modules'}
                        </span>
                      </div>
                      
                      {/* Horizontal Add Module Bar */}
                      <form onSubmit={(e) => handleAddModuleForWeek(e, weekNum)} className="add-module-form mb-4">
                        <input 
                          type="text" 
                          className="flex-1 px-4 py-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl text-xs font-medium text-slate-900 dark:text-white placeholder-slate-400 focus:outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/10 shadow-sm" 
                          placeholder={`Add module to Week ${weekNum}...`} 
                          value={newModTitles[weekNum] || ''} 
                          onChange={(e) => setNewModTitles({...newModTitles, [weekNum]: e.target.value})} 
                          required 
                        />
                        <button type="submit" className="px-5 py-3 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-extrabold rounded-2xl shadow-md hover:scale-105 active:scale-95 transition-all whitespace-nowrap flex items-center gap-1.5">
                          <HiOutlinePlus size={15} /> Add Module
                        </button>
                      </form>

                      <div className="outline-modules-list space-y-3">
                        {weekModules.length === 0 ? (
                          <div className="text-slate-400 text-xs py-3 text-center italic border border-dashed border-slate-200 dark:border-slate-800 rounded-2xl">
                            No modules added for Week {weekNum} yet.
                          </div>
                        ) : (
                          weekModules.map((mod) => (
                            <div key={mod._id} className="outline-module-container">
                              <div className="outline-module-header">
                                <span className="flex items-center gap-2 text-slate-900 dark:text-white font-extrabold text-sm">
                                  <HiOutlineBookOpen className="text-indigo-500 flex-shrink-0" size={17} /> 
                                  {mod.title}
                                </span>
                                <div className="outline-module-actions">
                                  <button 
                                    type="button" 
                                    className="px-3 py-1.5 text-xs font-extrabold text-indigo-600 bg-indigo-50 hover:bg-indigo-100 dark:bg-indigo-500/10 dark:text-indigo-400 dark:hover:bg-indigo-500/20 rounded-xl transition-all" 
                                    onClick={() => setActiveModuleId(activeModuleId === mod._id ? null : mod._id)}
                                  >
                                    {activeModuleId === mod._id ? 'Cancel' : '+ Lesson'}
                                  </button>
                                  <Link to={`/exams/${id}/create`} className="px-3 py-1.5 text-xs font-extrabold text-purple-600 bg-purple-50 hover:bg-purple-100 dark:bg-purple-500/10 dark:text-purple-400 dark:hover:bg-purple-500/20 rounded-xl transition-all">
                                    + Exam
                                  </Link>
                                  <button 
                                    type="button" 
                                    className="p-1.5 text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10 rounded-xl transition-colors" 
                                    onClick={() => handleDeleteModule(mod._id)}
                                    title="Delete Module"
                                  >
                                    <HiOutlineTrash size={16} />
                                  </button>
                                </div>
                              </div>

                              {/* Lessons list in module */}
                              {mod.lessons && mod.lessons.length > 0 && (
                                <div className="outline-lessons-list">
                                  {mod.lessons.map((les, idx) => (
                                    <div key={les._id} className="outline-lesson-item">
                                      <span className="flex items-center gap-2.5 text-slate-700 dark:text-slate-300 font-semibold text-xs">
                                        {['video', 'lecture', 'dpp-video'].includes(les.type) ? (
                                          <HiOutlinePlay className="text-indigo-500 flex-shrink-0" size={15} />
                                        ) : (
                                          <HiOutlineDocumentText className="text-indigo-500 flex-shrink-0" size={15} />
                                        )}
                                        <span>{idx + 1}. {les.title}</span>
                                        <span className="px-2 py-0.5 rounded-md bg-slate-100 dark:bg-white/5 text-[9px] font-extrabold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider">
                                          {les.type}
                                        </span>
                                      </span>
                                      <button 
                                        type="button" 
                                        className="p-1 text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10 rounded-lg transition-colors" 
                                        onClick={() => handleDeleteLesson(mod._id, les._id)}
                                        title="Delete Lesson"
                                      >
                                        <HiOutlineTrash size={14} />
                                      </button>
                                    </div>
                                  ))}
                                </div>
                              )}

                              {/* Add Lesson Form Box */}
                              {activeModuleId === mod._id && (
                                <div className="add-lesson-box">
                                  <div className="flex justify-between items-center pb-2 border-b border-slate-200 dark:border-white/10">
                                    <h4 className="text-xs font-black text-indigo-600 dark:text-indigo-400 uppercase tracking-wider flex items-center gap-1.5">
                                      <HiOutlineSparkles size={15} /> Add New Lesson to {mod.title}
                                    </h4>
                                    <button 
                                      type="button" 
                                      className="text-xs font-bold text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
                                      onClick={() => setActiveModuleId(null)}
                                    >
                                      ✕ Close
                                    </button>
                                  </div>
                                  
                                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                                    <div className="space-y-1">
                                      <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300">Lesson Title</label>
                                      <input 
                                        type="text" 
                                        className="w-full px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-medium text-slate-900 dark:text-white focus:outline-none focus:border-indigo-500" 
                                        placeholder="e.g. Setting Up Docker Containers"
                                        value={lessonForm.title} 
                                        onChange={(e) => setLessonForm({ ...lessonForm, title: e.target.value })} 
                                        required 
                                      />
                                    </div>

                                    <div className="space-y-1">
                                       <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300">Material Type</label>
                                       <CustomSelect
                                         id="lesson-type"
                                         name="type"
                                         value={lessonForm.type}
                                         onChange={(e) => setLessonForm({ ...lessonForm, type: e.target.value })}
                                         options={[
                                           { value: 'lecture', label: 'Lecture (Video Stream)' },
                                           { value: 'notes', label: 'Notes (Document / PDF)' },
                                           { value: 'dpp', label: 'DPP (Practice Quiz)' },
                                           { value: 'dpp-pdf', label: 'DPP PDF (Downloadable)' },
                                           { value: 'dpp-video', label: 'DPP Video (Solution)' },
                                           { value: 'video', label: 'Other Video Link' },
                                           { value: 'document', label: 'Other Text Material' },
                                         ]}
                                       />
                                     </div>
                                  </div>

                                  {['video', 'lecture', 'dpp-video'].includes(lessonForm.type) && (
                                    <div className="space-y-1">
                                      <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300">Video Stream URL</label>
                                      <input 
                                        type="url" 
                                        className="w-full px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-medium text-slate-900 dark:text-white" 
                                        placeholder="https://www.youtube.com/watch?v=..." 
                                        value={lessonForm.videoUrl} 
                                        onChange={(e) => setLessonForm({ ...lessonForm, videoUrl: e.target.value })} 
                                        required 
                                      />
                                    </div>
                                  )}

                                  {['notes', 'dpp-pdf', 'document'].includes(lessonForm.type) && (
                                    <div className="space-y-1">
                                      <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300">Attachment File (PDF, DOCX, ZIP)</label>
                                      <input 
                                        type="file" 
                                        className="w-full text-xs text-slate-500 file:mr-3 file:py-1.5 file:px-3 file:rounded-xl file:border-0 file:text-xs file:font-bold file:bg-indigo-50 file:text-indigo-600 dark:file:bg-indigo-950 dark:file:text-indigo-400 cursor-pointer" 
                                        onChange={(e) => setLessonFile(e.target.files[0])} 
                                      />
                                    </div>
                                  )}

                                  <div className="space-y-1">
                                    <div className="flex justify-between items-center">
                                      <label className="text-[11px] font-bold text-slate-700 dark:text-slate-300">Text Content / Summary</label>
                                      <button
                                        type="button"
                                        className="ai-generate-btn"
                                        onClick={handleGenerateLessonSummary}
                                        disabled={aiLoading}
                                      >
                                        <HiOutlineSparkles size={12} /> {aiLoading ? '...' : 'AI Summary'}
                                      </button>
                                    </div>
                                    <textarea 
                                      className="w-full p-2.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-medium text-slate-900 dark:text-white placeholder-slate-400" 
                                      placeholder="Optional lesson summary..." 
                                      value={lessonForm.content} 
                                      onChange={(e) => setLessonForm({ ...lessonForm, content: e.target.value })} 
                                    />
                                  </div>

                                  <div className="flex justify-end gap-2 pt-1">
                                    <button 
                                      type="button" 
                                      className="px-4 py-2 bg-slate-100 dark:bg-white/5 text-slate-600 dark:text-slate-300 hover:bg-slate-200 text-xs font-extrabold rounded-xl transition-all cursor-pointer" 
                                      onClick={() => setActiveModuleId(null)}
                                    >
                                      Cancel
                                    </button>
                                    <button 
                                      type="button" 
                                      className="px-5 py-2 bg-gradient-to-r from-indigo-600 to-purple-600 text-white text-xs font-extrabold rounded-xl shadow-md hover:scale-105 active:scale-95 transition-all cursor-pointer" 
                                      onClick={(e) => handleAddLesson(e, mod._id)}
                                    >
                                      Save Lesson →
                                    </button>
                                  </div>
                                </div>
                              )}
                            </div>
                          ))
                        )}
                      </div>
                    </div>
                  );
                });
              })()}
            </div>

            {/* Bottom Footer Actions */}
            <div className="pt-6 mt-6 border-t border-slate-200 dark:border-slate-800 flex flex-wrap items-center justify-between gap-4">
              <button
                type="button"
                className="px-6 py-3 bg-slate-100 hover:bg-slate-200 dark:bg-white/5 dark:hover:bg-white/10 text-slate-700 dark:text-slate-200 font-extrabold text-xs rounded-2xl transition-all flex items-center gap-2 cursor-pointer"
                onClick={() => setActiveTab('details')}
              >
                <HiOutlineArrowLeft size={16} /> Back to Course Settings
              </button>

              <div className="flex items-center gap-3 flex-wrap">
                <button
                  type="button"
                  onClick={handleTogglePublish}
                  className={`px-6 py-3 rounded-2xl font-extrabold text-xs transition-all flex items-center gap-2 cursor-pointer shadow-md ${
                    form.isPublished 
                      ? 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/30 hover:bg-amber-500/20' 
                      : 'bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white shadow-emerald-500/25 hover:scale-105 active:scale-95'
                  }`}
                >
                  <HiOutlineGlobeAlt size={16} />
                  {form.isPublished ? 'Unpublish Course (Draft)' : 'Publish Course Live 🌐'}
                </button>
                <Link
                  to={`/course/${id}`}
                  className="px-6 py-3 border border-slate-200 dark:border-white/10 hover:border-indigo-500 text-slate-700 dark:text-slate-200 font-extrabold text-xs rounded-2xl transition-all flex items-center gap-2"
                >
                  Preview Course Page
                </Link>
                <Link
                  to="/dashboard"
                  className="px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-extrabold text-xs rounded-2xl transition-all shadow-md flex items-center gap-2"
                >
                  <HiOutlineCheckCircle size={16} /> Return to Dashboard
                </Link>
              </div>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default CourseCreate;
