import { useState, useEffect } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { createCourse, getCourseById, updateCourse, createModule, createLesson, deleteModule, deleteLesson, togglePublish } from '../api/courseApi';
import { generateCourseDescription, generateLessonSummary } from '../api/aiApi';
import toast from 'react-hot-toast';
import { CATEGORIES, DIFFICULTIES, STRUCTURE_TYPES } from '../utils/constants';
import './CourseCreate.css';

const CourseCreate = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEdit = !!id;

  const [form, setForm] = useState({
    title: '',
    description: '',
    shortDescription: '',
    category: 'web-development',
    difficulty: 'beginner',
    structureType: 'topic-based',
    price: 0,
    estimatedDuration: '',
  });
  const [imageFile, setImageFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isPublished, setIsPublished] = useState(false);
  const [modules, setModules] = useState([]);
  const [newModTitle, setNewModTitle] = useState('');
  const [extraWeeks, setExtraWeeks] = useState([]);
  const [newModTitles, setNewModTitles] = useState({});
  
  // Lesson outline states
  const [activeModuleId, setActiveModuleId] = useState(null);
  const [lessonFile, setLessonFile] = useState(null);
  const [lessonForm, setLessonForm] = useState({
    title: '',
    type: 'lecture',
    videoUrl: '',
    content: '',
  });

  const [aiLoading, setAiLoading] = useState(false);

  const handleGenerateCourseDesc = async () => {
    if (!form.title.trim()) {
      toast.error('Please enter a course title first to guide the AI!');
      return;
    }
    setAiLoading(true);
    try {
      const res = await generateCourseDescription(form.title, form.category);
      setForm(prev => ({ ...prev, description: res.data.data.description }));
      toast.success('Course description generated by Gemini!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'AI generation failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleGenerateLessonSummary = async () => {
    if (!lessonForm.title.trim()) {
      toast.error('Please enter a lesson title first to guide the AI!');
      return;
    }
    setAiLoading(true);
    try {
      const res = await generateLessonSummary(lessonForm.title, lessonForm.content || '');
      setLessonForm(prev => ({ ...prev, content: res.data.data.summary }));
      toast.success('Lesson summary generated by Gemini!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'AI generation failed');
    } finally {
      setAiLoading(false);
    }
  };

  const handleAddLesson = async (e, moduleId) => {
    e.preventDefault();
    if (!lessonForm.title.trim()) return;
    try {
      let res;
      if (lessonFile || ['notes', 'dpp-pdf', 'document'].includes(lessonForm.type)) {
        const formData = new FormData();
        formData.append('title', lessonForm.title);
        formData.append('type', lessonForm.type);
        formData.append('content', lessonForm.content);
        formData.append('videoUrl', lessonForm.videoUrl);
        formData.append('courseId', id);
        if (lessonFile) {
          formData.append('attachments', lessonFile);
        }
        res = await createLesson(moduleId, formData);
      } else {
        res = await createLesson(moduleId, { ...lessonForm, courseId: id });
      }
      
      // Update modules state list
      const updated = modules.map(m => {
        if (m._id === moduleId) {
          return { ...m, lessons: [...(m.lessons || []), res.data.data] };
        }
        return m;
      });
      setModules(updated);
      
      // Reset form
      setLessonForm({ title: '', type: 'lecture', videoUrl: '', content: '' });
      setLessonFile(null);
      setActiveModuleId(null);
      toast.success('Lesson successfully added!');
    } catch (err) {
      console.error(err);
      toast.error('Failed to add lesson to module');
    }
  };

  useEffect(() => {
    if (isEdit) {
      const loadCourse = async () => {
        try {
          const res = await getCourseById(id);
          const c = res.data.data;
          setForm({
            title: c.title,
            description: c.description,
            shortDescription: c.shortDescription || '',
            category: c.category,
            difficulty: c.difficulty,
            structureType: c.structureType,
            price: c.price || 0,
            estimatedDuration: c.estimatedDuration || '',
          });
          setModules(c.modules || []);
          setIsPublished(c.isPublished || false);
        } catch {
          toast.error('Failed to load course for editing');
        }
      };
      loadCourse();
    }
  }, [id, isEdit]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const formData = new FormData();
      Object.keys(form).forEach(key => formData.append(key, form[key]));
      if (imageFile) formData.append('thumbnail', imageFile);

      if (isEdit) {
        await updateCourse(id, formData);
        toast.success('Course updated successfully!');
      } else {
        const res = await createCourse(formData);
        toast.success('Course created successfully!');
        navigate(`/course/${res.data.data._id}/edit`);
      }
    } catch {
      toast.error('Failed to save course');
    } finally {
      setLoading(false);
    }
  };

  const handleAddModule = async (e) => {
    e.preventDefault();
    if (!newModTitle.trim() || !id) return;
    try {
      const res = await createModule(id, { title: newModTitle.trim(), week: 1 });
      setModules([...modules, res.data.data]);
      setNewModTitle('');
      toast.success('Module added!');
    } catch {
      toast.error('Failed to add module');
    }
  };

  const handleAddModuleForWeek = async (e, weekNum) => {
    e.preventDefault();
    const title = newModTitles[weekNum];
    if (!title || !title.trim() || !id) return;
    try {
      const res = await createModule(id, { title: title.trim(), week: weekNum });
      setModules([...modules, res.data.data]);
      setNewModTitles(prev => ({ ...prev, [weekNum]: '' }));
      toast.success(`Module added to Week ${weekNum}!`);
    } catch {
      toast.error('Failed to add module');
    }
  };

  const handleDeleteModule = async (moduleId) => {
    if (!window.confirm('Are you sure you want to delete this module? This will remove the module heading (lessons can be re-assigned).')) return;
    try {
      await deleteModule(moduleId);
      setModules(modules.filter(m => m._id !== moduleId));
      toast.success('Module deleted!');
    } catch {
      toast.error('Failed to delete module');
    }
  };

  const handleDeleteLesson = async (moduleId, lessonId) => {
    if (!window.confirm('Are you sure you want to delete this lesson?')) return;
    try {
      await deleteLesson(lessonId);
      setModules(modules.map(m => {
        if (m._id === moduleId) {
          return { ...m, lessons: m.lessons.filter(l => l._id !== lessonId) };
        }
        return m;
      }));
      toast.success('Lesson deleted!');
    } catch {
      toast.error('Failed to delete lesson');
    }
  };

  const handleTogglePublish = async () => {
    try {
      const res = await togglePublish(id);
      setIsPublished(res.data.data.isPublished);
      toast.success(`Course ${res.data.data.isPublished ? 'published' : 'unpublished'} successfully!`);
    } catch {
      toast.error('Failed to toggle publish status');
    }
  };

  return (
    <div className="create-course-page animate-page-enter">
      <div className="flex justify-between items-center mb-md" style={{ flexWrap: 'wrap', gap: '15px' }}>
        <h1 className="text-4xl font-bold font-heading text-slate-900 dark:text-white" style={{ margin: 0 }}>
          {isEdit ? 'Edit' : 'Create'} <span className="gradient-text">Course</span>
        </h1>
        {isEdit && (
          <div className="flex items-center gap-2">
            <span className={`badge ${isPublished ? 'badge-success' : 'badge-accent'}`}>
              {isPublished ? 'Published' : 'Draft'}
            </span>
            <button type="button" className="btn btn-outline btn-sm" onClick={handleTogglePublish}>
              {isPublished ? 'Unpublish Course' : 'Publish Course'}
            </button>
          </div>
        )}
      </div>
      
      <div className={`create-course-layout animate-slide-up delay-1 ${isEdit ? 'is-edit' : 'is-create'}`}>
        <form onSubmit={handleSubmit} className="create-course-form glass-card" id="course-create-form">
          <div className="input-group">
            <label htmlFor="course-title">Course Title</label>
            <input id="course-title" type="text" className="input-field" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required />
          </div>

          <div className="input-group">
            <label htmlFor="course-short-desc">Short Description</label>
            <input id="course-short-desc" type="text" className="input-field" placeholder="Brief summary of the course..." value={form.shortDescription} onChange={(e) => setForm({ ...form, shortDescription: e.target.value })} />
          </div>

          <div className="input-group">
            <div className="flex justify-between items-center mb-xs">
              <label htmlFor="course-description">Full Description</label>
              <button
                type="button"
                className="ai-generate-btn"
                onClick={handleGenerateCourseDesc}
                disabled={aiLoading}
              >
                {aiLoading ? 'Generating...' : '✨ Generate by AI'}
              </button>
            </div>
            <textarea id="course-description" className="input-field textarea-large" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} required />
          </div>

          <div className="grid grid-2">
            <div className="input-group">
              <label htmlFor="course-category">Category</label>
              <select id="course-category" className="input-field" value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>
                {CATEGORIES.map(c => <option key={c.value} value={c.value}>{c.label}</option>)}
              </select>
            </div>
            <div className="input-group">
              <label htmlFor="course-diff">Difficulty Level</label>
              <select id="course-diff" className="input-field" value={form.difficulty} onChange={(e) => setForm({ ...form, difficulty: e.target.value })}>
                {DIFFICULTIES.map(d => <option key={d.value} value={d.value}>{d.label}</option>)}
              </select>
            </div>
          </div>

          <div className="grid grid-3">
            <div className="input-group">
              <label htmlFor="course-structure">Structure Mode</label>
              <select id="course-structure" className="input-field" value={form.structureType} onChange={(e) => setForm({ ...form, structureType: e.target.value })} disabled={isEdit}>
                {STRUCTURE_TYPES.map(s => <option key={s.value} value={s.value}>{s.label}</option>)}
              </select>
            </div>
            <div className="input-group">
              <label htmlFor="course-price">Price ($)</label>
              <input id="course-price" type="number" min="0" className="input-field" value={form.price} onChange={(e) => setForm({ ...form, price: parseFloat(e.target.value) || 0 })} />
            </div>
            <div className="input-group">
              <label htmlFor="course-duration">Est. Duration</label>
              <input id="course-duration" type="text" placeholder="e.g. 4 weeks, 20 hours" className="input-field" value={form.estimatedDuration} onChange={(e) => setForm({ ...form, estimatedDuration: e.target.value })} />
            </div>
          </div>

          <div className="input-group">
            <label htmlFor="course-thumbnail">Thumbnail Image</label>
            <input id="course-thumbnail" type="file" accept="image/*" onChange={(e) => setImageFile(e.target.files[0])} />
          </div>

          <button type="submit" className="btn btn-primary btn-lg" disabled={loading}>
            {loading ? 'Saving...' : 'Save Course'}
          </button>
        </form>

        {isEdit && (
          <div className="create-course-outline glass-card">
            <div className="flex justify-between items-center mb-md">
              <h3 style={{ margin: 0 }}>Course Curriculum Outline</h3>
              <button 
                type="button" 
                className="btn btn-accent btn-sm" 
                onClick={() => {
                  const weeks = Array.from(new Set([1, ...modules.map(m => m.week || 1), ...extraWeeks]));
                  const nextWeek = Math.max(...weeks, 0) + 1;
                  setExtraWeeks([...extraWeeks, nextWeek]);
                }}
              >
                + Add Week
              </button>
            </div>

            <div className="weeks-list">
              {(() => {
                const weeks = Array.from(new Set([1, ...modules.map(m => m.week || 1), ...extraWeeks])).sort((a, b) => a - b);
                return weeks.map((weekNum) => {
                  const weekModules = modules.filter(m => (m.week || 1) === weekNum);
                  return (
                    <div key={weekNum} className="week-section mb-lg" style={{ border: '1px dashed var(--border-color)', borderRadius: 'var(--radius-md)', padding: 'var(--space-md)', background: 'rgba(255, 255, 255, 0.02)' }}>
                      <h4 className="text-lg font-bold mb-md" style={{ color: 'var(--color-primary-light)', borderBottom: '1px solid var(--border-color)', paddingBottom: '4px' }}>
                        📅 Week {weekNum}
                      </h4>
                      
                      <form onSubmit={(e) => handleAddModuleForWeek(e, weekNum)} className="add-module-form mb-md" style={{ display: 'flex', gap: '8px', flexDirection: 'row', alignItems: 'center' }}>
                        <input type="text" className="input-field" style={{ flex: 1, height: '36px' }} placeholder="New Module Title..." value={newModTitles[weekNum] || ''} onChange={(e) => setNewModTitles({...newModTitles, [weekNum]: e.target.value})} required />
                        <button type="submit" className="btn btn-primary btn-sm" style={{ whiteSpace: 'nowrap', height: '36px' }}>Add Module</button>
                      </form>

                      <div className="outline-modules-list">
                        {weekModules.length === 0 ? (
                          <div className="text-slate-400 text-xs py-2">No modules in this week.</div>
                        ) : (
                          weekModules.map((mod) => (
                            <div key={mod._id} className="outline-module-container mb-sm">
                              <div className="outline-module-header">
                                <span>📦 {mod.title}</span>
                                <div className="outline-module-actions flex items-center gap-2">
                                  <button type="button" className="btn btn-ghost btn-sm" onClick={() => setActiveModuleId(activeModuleId === mod._id ? null : mod._id)}>
                                    {activeModuleId === mod._id ? 'Cancel' : '+ Add Lesson'}
                                  </button>
                                  <Link to={`/exams/${id}/create`} className="btn btn-ghost btn-sm">Add Exam</Link>
                                  <button type="button" className="btn btn-ghost btn-sm" style={{ color: '#ef4444', padding: '4px 8px', minHeight: 'unset' }} onClick={() => handleDeleteModule(mod._id)}>Delete</button>
                                </div>
                              </div>

                              {/* Lessons in this module */}
                              {mod.lessons && mod.lessons.length > 0 && (
                                <div className="outline-lessons-list">
                                  {mod.lessons.map((les, idx) => (
                                    <div key={les._id} className="outline-lesson-item flex justify-between items-center" style={{ padding: '8px 12px' }}>
                                      <span>📄 {idx + 1}. {les.title} <span className="badge badge-primary">{les.type}</span></span>
                                      <button type="button" className="btn btn-ghost btn-sm" style={{ color: '#ef4444', padding: '2px 6px', minHeight: 'unset' }} onClick={() => handleDeleteLesson(mod._id, les._id)}>Delete</button>
                                    </div>
                                  ))}
                                </div>
                              )}

                              {/* Add Lesson Form */}
                              {activeModuleId === mod._id && (
                                <div className="add-lesson-box glass-card">
                                  <h4>New Lesson Details</h4>
                                  <div className="input-group">
                                    <label>Title</label>
                                    <input type="text" className="input-field" value={lessonForm.title} onChange={(e) => setLessonForm({ ...lessonForm, title: e.target.value })} required />
                                  </div>
                                  <div className="input-group">
                                    <label>Material Type</label>
                                    <select className="input-field" value={lessonForm.type} onChange={(e) => setLessonForm({ ...lessonForm, type: e.target.value })}>
                                      <option value="lecture">Lecture (Video)</option>
                                      <option value="notes">Notes (Document / PDF)</option>
                                      <option value="dpp">DPP (Practice Quiz)</option>
                                      <option value="dpp-pdf">DPP PDF (Downloadable)</option>
                                      <option value="dpp-video">DPP Video (Solution)</option>
                                      <option value="video">Other Video Link</option>
                                      <option value="document">Other Text Material</option>
                                    </select>
                                  </div>
                                  {['video', 'lecture', 'dpp-video'].includes(lessonForm.type) && (
                                    <div className="input-group">
                                      <label>Video URL (YouTube or Vimeo link)</label>
                                      <input type="url" className="input-field" placeholder="https://www.youtube.com/watch?v=... or https://youtu.be/..." value={lessonForm.videoUrl} onChange={(e) => setLessonForm({ ...lessonForm, videoUrl: e.target.value })} required />
                                    </div>
                                  )}
                                  {['notes', 'dpp-pdf', 'document'].includes(lessonForm.type) && (
                                    <div className="input-group">
                                      <label>Attachment File (PDF, DOCX, ZIP)</label>
                                      <input type="file" className="input-field" onChange={(e) => setLessonFile(e.target.files[0])} />
                                    </div>
                                  )}
                                  <div className="input-group">
                                    <div className="flex justify-between items-center mb-xs">
                                      <label>Text Content / Summary</label>
                                      <button
                                        type="button"
                                        className="ai-generate-btn"
                                        onClick={handleGenerateLessonSummary}
                                        disabled={aiLoading}
                                      >
                                        {aiLoading ? 'Generating...' : '✨ Generate Summary'}
                                      </button>
                                    </div>
                                    <textarea className="input-field textarea-large" placeholder="Optional description..." value={lessonForm.content} onChange={(e) => setLessonForm({ ...lessonForm, content: e.target.value })} />
                                  </div>
                                  <button type="button" className="btn btn-accent btn-sm" onClick={(e) => handleAddLesson(e, mod._id)}>
                                    Add Lesson
                                  </button>
                                </div>
                              )}
                            </div>
                          ))
                        )}
                      </div>
                    </div>
                  );
                });
              })()}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default CourseCreate;
